default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: task
  port: 5432

development:
  <<: *default
  database: task-4_development

test:
  <<: *default
  database: task-4_test

production:
  <<: *default
  database: task-4_production
  username: task-4
  password: <%= ENV['TASK-4_DATABASE_PASSWORD'] %>
